// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvpX-SBKX3DY66PSuHszxiijVE1UuGcEE',
    appId: '1:767357647694:web:ee58ed68beb7cc1c443c1f',
    messagingSenderId: '767357647694',
    projectId: 'buy-book-pop',
    authDomain: 'buy-book-pop.firebaseapp.com',
    storageBucket: 'buy-book-pop.appspot.com',
    measurementId: 'G-N6WZ3DEYLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wkjFeKAA3CQXD0BrYiIadamXmmBO9Co',
    appId: '1:767357647694:android:7a0ac5f9bba39b2a443c1f',
    messagingSenderId: '767357647694',
    projectId: 'buy-book-pop',
    storageBucket: 'buy-book-pop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUHq8IjDe4ci9bxrqWBrJc2-sEwdPPagU',
    appId: '1:767357647694:ios:ad17ecae485dc185443c1f',
    messagingSenderId: '767357647694',
    projectId: 'buy-book-pop',
    storageBucket: 'buy-book-pop.appspot.com',
    iosClientId: '767357647694-0ancv8tcu6njhc3def171dhbfg83vri2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebPop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUHq8IjDe4ci9bxrqWBrJc2-sEwdPPagU',
    appId: '1:767357647694:ios:ad17ecae485dc185443c1f',
    messagingSenderId: '767357647694',
    projectId: 'buy-book-pop',
    storageBucket: 'buy-book-pop.appspot.com',
    iosClientId: '767357647694-0ancv8tcu6njhc3def171dhbfg83vri2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebPop',
  );
}
